name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test -v ./...

    - name: Run coverage tests
      run: go test -coverprofile=coverage.out ./...

    - name: Build project
      run: go build -o url-shortener

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        file: coverage.out
